# Base16 Brush Trees Dark - ncspot color config
# Abraham White &lt;abelincoln.white@gmail.com&gt;

[theme]
background = "#485867"
primary = "#b0c5c8"
secondary = "#5a6d7a"
title = "#c9dbdc"
playing = "#c9dbdc"
playing_bg = "#485867"
highlight = "#b0c5c8"
highlight_bg = "#6d828e"
error = "#b0c5c8"
error_bg = "#e3efef"
statusbar = "#485867"
statusbar_progress = "#c9dbdc"
statusbar_bg = "#c9dbdc"
cmdline = "#b0c5c8"
cmdline_bg = "#485867"
