# Base16 Brogrammer - ncspot color config
# Vik Ramanujam (http://github.com/piggyslasher)

[theme]
background = "#1f1f1f"
primary = "#4e5ab7"
secondary = "#f81118"
title = "#1081d6"
playing = "#1081d6"
playing_bg = "#1f1f1f"
highlight = "#4e5ab7"
highlight_bg = "#2dc55e"
error = "#4e5ab7"
error_bg = "#d6dbe5"
statusbar = "#1f1f1f"
statusbar_progress = "#1081d6"
statusbar_bg = "#1081d6"
cmdline = "#4e5ab7"
cmdline_bg = "#1f1f1f"
