# Base16 Classic Light - ncspot color config
# Jason Heeris (http://heeris.id.au)

[theme]
background = "#f5f5f5"
primary = "#303030"
secondary = "#e0e0e0"
title = "#202020"
playing = "#202020"
playing_bg = "#f5f5f5"
highlight = "#303030"
highlight_bg = "#d0d0d0"
error = "#303030"
error_bg = "#151515"
statusbar = "#f5f5f5"
statusbar_progress = "#202020"
statusbar_bg = "#202020"
cmdline = "#303030"
cmdline_bg = "#f5f5f5"
