# Base16 Flat - ncspot color config
# Chris Kempson (http://chriskempson.com)

[theme]
background = "#2c3e50"
primary = "#e0e0e0"
secondary = "#34495e"
title = "#f5f5f5"
playing = "#f5f5f5"
playing_bg = "#2c3e50"
highlight = "#e0e0e0"
highlight_bg = "#7f8c8d"
error = "#e0e0e0"
error_bg = "#ecf0f1"
statusbar = "#2c3e50"
statusbar_progress = "#f5f5f5"
statusbar_bg = "#f5f5f5"
cmdline = "#e0e0e0"
cmdline_bg = "#2c3e50"
