# Base16 Monokai - ncspot color config
# Wimer Hazenberg (http://www.monokai.nl)

[theme]
background = "#272822"
primary = "#f8f8f2"
secondary = "#383830"
title = "#f5f4f1"
playing = "#f5f4f1"
playing_bg = "#272822"
highlight = "#f8f8f2"
highlight_bg = "#49483e"
error = "#f8f8f2"
error_bg = "#f9f8f5"
statusbar = "#272822"
statusbar_progress = "#f5f4f1"
statusbar_bg = "#f5f4f1"
cmdline = "#f8f8f2"
cmdline_bg = "#272822"
